export enum Type {
    CREATE_APARTMENT = "CREATE_APARTMENT",
    CREATE_ROOM = "CREATE_ROOM",
    CREATE_BED = "CREATE_BED",

    UPDATE_IMAGE= "UPDATE_IMAGE",
    DELETE_IMAGE = "DELETE_IMAGE",
    UPLOAD_IMAGE = "UPLOAD_IMAGE",

    UPDATE_APARTMENT = "UPDATE_APARTMENT",
    UPDATE_ROOM = "UPDATE_ROOM",
    UPDATE_BED = "UPDATE_BED",

    DELETE_APARTMENT = "DELETE_APARTMENT",
    DELETE_ROOM = "DELETE_ROOM",
    DELETE_BED = "DELETE_BED",

    PROFILE_COMPLETE = "PROFILE_COMPLETE",
    PROFILE_UPDATE = "PROFILE_UPDATE",

    

}