export enum Type {
    UPLOAD_APARTMENT = "UPLOAD_APARTMENT",
    UPLOAD_ROOM = "UPLOAD_ROOM",
    UPLOAD_BED = "UPLOAD_BED",

    UPDATE_APARTMENT = "UPDATE_APARTMENT",
    UPDATE_ROOM = "UPDATE_ROOM",
    UPDATE_BED = "UPDATE_BED",

    DELETE_APARTMENT = "DELETE_APARTMENT",
    DELETE_ROOM = "DELETE_ROOM",
    DELETE_BED = "DELETE_BED",

    PROFILE_COMPLETE = "PROFILE_COMPLETE",
    PROFILE_UPDATE = "PROFILE_UPDATE",
    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD",

}